# The URL the site will be built for
base_url = "https://blog.rockorrest.com"
title = "Rocky Le | ROCK your challenges, or rest on your execuses"
description = "Trang blog này được xây dựng với mục đích ghi lại sự phát triển bản thân của tác giả (Rocky), đồng thời cũng nhằm tạo thêm những giá trị khác cho cộng đồng."
generate_feed = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [  
  {name = "chuyen-muc", feed = true},
  {name = "the", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Rocky Le"
email = "rocky@alasts.com"
github = "https://github.com/rockyle244"
twitter = "https://twitter.com/rockyle244"
no_feature_image_placeholder = "/assets/img/no-feature-image-placeholder.jpg"
header_menu = [
  {url = "$BASE_URL/bai-viet/", name = "Bài Viết", slash = true},
  {url = "$BASE_URL/chuyen-muc/", name = "Chuyên Mục", slash = true},
  {url = "$BASE_URL/the/", name = "Thẻ", slash = true},
]
# Rel Icons
rel_icon_path = "/assets/img/favicon.png"
rel_apple_touch_icon_path = "/assets/img/apple-touch-icon.png"
# Vendor Style Files
vendor_css_bootstrap = "/assets/vendor/bootstrap/css/bootstrap.min.css"
vendor_css_bootstrap_icons = "/assets/vendor/bootstrap-icons/bootstrap-icons.css"
vendor_css_swiper = "/assets/vendor/swiper/swiper-bundle.min.css"
vendor_css_glightbox = "/assets/vendor/glightbox/css/glightbox.min.css"
vendor_css_aos = "/assets/vendor/aos/aos.css"
# Main Style Files
css_variables = "/assets/css/variables.css"
css_main = "/assets/css/blog.css"
# Vendor JS Files
vendor_js_bootstrap = "/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"
vendor_js_swiper = "/assets/vendor/swiper/swiper-bundle.min.js"
vendor_js_glightbox = "/assets/vendor/glightbox/js/glightbox.min.js"
vendor_js_aos = "/assets/vendor/aos/aos.js"
# Main JS File
js_main = "/assets/js/blog.js"
